version: '3.6'

networks:
  network:
    driver: bridge

services:
  xilften_app:
    container_name: xilften_app
    build: './xilften'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks: 
      - network
    depends_on: 
      - xilften_api

  xilften_api:
    build: './Backend'
    environment:
      - MONGO_URL=db
    command: yarn dev:server
    depends_on:
      - xilften_db
      - xilften_redis
    networks:
      - network
    links:
      - xilften_db
      - xilften_redis
    container_name: xilften_api
    ports:
      - 3333:3333
  
  xilften_queue:
    build: './Backend'
    environment:
      - MONGO_URL=db
      - REDIS_HOST=xilften_redis
    depends_on:
      - xilften_db
      - xilften_redis
    networks:
      - network
    links:
      - xilften_db
      - xilften_redis 
    container_name: xilften_queue
    command: yarn dev:queue

  xilften_db:
    image: bitnami/mongodb:latest
    container_name: xilften_db
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - network

  xilften_redis:
    image: redis
    command: redis-server --requirepass xilften
    container_name: xilften_redis
    ports: 
      - 6379:6379
    networks: 
      - network
    volumes: 
      - redis_data:/data
      
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local